[package]
name = "cetz-mechanical-system-34j"
version = "1.0.5"
entrypoint = "src/lib.typ"
authors = ["34j <@34j>"]
categories = ["visualization"]
keywords = ["cetz", "draw"]
license = "MIT"
repository = "https://github.com/34j/typst-cetz-mechanical-system"
description = "CeTZ library for drawing mechanical systems."
exclude = ["tests/*", "*.png"]
